GoalBasedMvc/GoalBasedMvc/Models/Network/Network.cs
using GoalBasedMvc.Logic;
using System.Collections.Generic;
using System.Linq;

namespace GoalBasedMvc.Models
{
    public interface INetwork
    {
        string Url { get; set; }
        string Name { get; set; }
        IDictionary<int, INode> Nodes { get; set; }
        IPortfolio Portfolio { get; }
        IList<CashFlow> CashFlows { get; set; }

        void Calculate();
    }

    public class Network : INetwork
    {
        private readonly INodeSimulator _nodeSimulator;

        public Network(
            IPortfolio portfolio, 
            INodeSimulator nodeSimulator
            )
        {
            Portfolio = portfolio;
            _nodeSimulator = nodeSimulator;
        }

        public string Url { get; set; }

        public string Name { get; set; }

        public IDictionary<int, INode> Nodes { get; set; }

        public IPortfolio Portfolio { get;}

        public IList<CashFlow> CashFlows { get; set; }

        public void Calculate()
        {
            Nodes = SimulateNodes(Nodes);
            IList<INode> nodes = Nodes.Values.ToList();
            IList<CashFlow> cashFlows = CashFlows.ToList();
            IList<INode> portfolioNodes = nodes.Where(n => n.IsPortfolioComponent).ToList();
            portfolioNodes = SetPortfolio(portfolioNodes, Portfolio);
            Portfolio.Init(portfolioNodes, cashFlows);
        }

        private IDictionary<int, INode> SimulateNodes(IDictionary<int, INode> nodes)
        {
            var nodeSimulations = _nodeSimulator.SimulateNodes(nodes);
            foreach (var key in nodes.Keys)
            {
                nodes[key].Simulations = nodeSimulations[key];
            }
            return nodes;
        }

        private IList<INode> SetPortfolio(IList<INode> portfolioNodes, IPortfolio portfolio)
        {
            foreach (var node in portfolioNodes)
            {
                node.Portfolio = portfolio;
            }

            return portfolioNodes;
        }

    }
}

GoalBasedMvc/GoalBasedMvc/Models/Network/NetworkEditViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;

namespace GoalBasedMvc.Models
{
    public class NetworkEditViewModel
    {
        public SortedDictionary<int, NodeEditViewModel> Nodes { get; set; }

        public IList<CashFlow> CashFlows { get; set; }

    }


}

GoalBasedMvc/GoalBasedMvc/Models/Network/NetworkRecord.cs
namespace GoalBasedMvc.Models
{
    public class NetworkRecord
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
    }
}

GoalBasedMvc/GoalBasedMvc/Models/Network/NetworkViewModel.cs
using System.Collections.Generic;

namespace GoalBasedMvc.Models
{
    public class NetworkViewModel
    {
        public string Url { get; set; }
        public string Name { get; set; }
        public IDictionary<int, NodeViewModel> Nodes { get; set; }
        public PortfolioViewModel Portfolio { get; set; }
        public IList<CashFlow> CashFlows { get; set; }

    }


}

GoalBasedMvc/GoalBasedMvc/Models/Node/INode.cs
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Linq;

namespace GoalBasedMvc.Models
{
    public interface INode
    {
        int Id { get; set; }
        string Name { get; set; }
        string Url { get; set; }
        string NetworkName { get; set; }
        string NetworkUrl { get; set; }
        double? InitialPrice { get; set; }
        double? InitialInvestment { get; set; }
        double? PortfolioWeight { get; set; }
        bool IsPortfolioComponent { get; set; }

        IList<IDistribution> Distributions { get; set; }

        INode Parent { get; set; }
    }

    public class Node:INode
    {
        private readonly IStatistic _statistic;
        private readonly IHistogram _histogram;

        public Node(
            IStatistic statistic,
            IHistogram histogram
            )
        {
            _statistic = statistic;
            _histogram = histogram;
            Distributions = new List<IDistribution>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
        public string NetworkName { get; set; }
        public string NetworkUrl { get; set; }
        public double? InitialPrice { get; set; }
        public double? InitialInvestment { get; set; }
        public double? PortfolioWeight { get; set; }
        public bool IsPortfolioComponent { get; set; }

        public IList<IDistribution> Distributions { get; set; }

        public IStatistic Statistics {
            get {
                var prices = Simulations.Select(s => s.Price).ToList();
                _statistic.Init(prices);
                return _statistic;
            }
        }

        public IList<HistogramDatum> Histogram
        {
            get
            {
                var context = new HistogramContext();
                context.Simulations = Simulations.Select(s => s.Price).ToList();
                context.GlobalXMin = Distributions.Min(d => d.Minimum);
                context.GlobalXMax = Distributions.Max(d => d.Maximum);
                var data = _histogram.GetHistogramData(context);
                return data;
            }
        }

        [JsonIgnore]
        public IList<Simulation> Simulations { get; set; }
        [JsonIgnore]
        public double[,] CumulativeSimulations { get; set; }
        [JsonIgnore]
        public double[,] ValueSimulations { get; set; }

        public INode Parent { get; set; }

    }
}

GoalBasedMvc/GoalBasedMvc/Models/Node/Node.cs
using System.Collections.Generic;
using System.Linq;

namespace GoalBasedMvc.Models
{
    public interface INode
    {
        int Id { get; set; }
        string Name { get; set; }
        string Url { get; set; }
        string NetworkName { get; set; }
        string NetworkUrl { get; set; }
        double? InitialPrice { get; set; }
        double? InitialInvestment { get; set; }
        double? PortfolioWeight { get; }
        bool IsPortfolioComponent { get; set; }

        IList<IDistribution> Distributions { get; set; }
        IStatistic Statistics { get; }
        IList<HistogramDatum> Histogram { get; }

        IList<double> Simulations { get; set; }

        INode Parent { get; set; }
        IPortfolio Portfolio { set; }
    }

    public class Node : INode
    {
        private readonly IStatistic _statistic;
        private readonly IHistogram _histogram;

        public Node(
            IStatistic statistic,
            IHistogram histogram
            )
        {
            _statistic = statistic;
            _histogram = histogram;
            Distributions = new List<IDistribution>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
        public string NetworkName { get; set; }
        public string NetworkUrl { get; set; }
        public double? InitialPrice { get; set; }
        public double? InitialInvestment { get; set; }
        public bool IsPortfolioComponent { get; set; }

        public double? PortfolioWeight
        {
            get
            {
                if (InitialInvestment.HasValue && Portfolio != null)
                {
                    return InitialInvestment / Portfolio.InitialValue;
                }
                return null;
            }
        }

        public IList<IDistribution> Distributions { get; set; }

        public IStatistic Statistics
        {
            get
            {
                _statistic.Init(Simulations);
                return _statistic;
            }
        }

        public IList<HistogramDatum> Histogram
        {
            get
            {
                var context = new HistogramContext();
                context.Simulations = Simulations;
                context.GlobalXMin = Distributions.Min(d => d.Minimum);
                context.GlobalXMax = Distributions.Max(d => d.Maximum);
                var data = _histogram.GetHistogramData(context);
                return data;
            }
        }

        public IList<double> Simulations { get; set; }

        public IPortfolio Portfolio { private get; set; }

        public INode Parent { get; set; }

    }
}

GoalBasedMvc/GoalBasedMvc/Models/Node/NodeEditViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace GoalBasedMvc.Models
{
    public class NodeEditViewModel
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public double? InitialPrice { get; set; }

        public double? InitialInvestment { get; set; }

        public double? PortfolioWeight { get; set; }

        public bool IsPortfolioComponent { get; set; }

        public IList<DistributionEditViewModel> Distributions { get; set; }

        public NodeEditViewModel Parent { get; set; }
    }

}

GoalBasedMvc/GoalBasedMvc/Models/Node/NodeRecord.cs
using System.Collections.Generic;

namespace GoalBasedMvc.Models
{
    public class NodeRecord
    {
        public NodeRecord()
        {
            Distributions = new List<DistributionRecord>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
        public string NetworkName { get; set; }
        public string NetworkUrl { get; set; }
        public double? InitialPrice { get; set; }
        public double? InitialInvestment { get; set; }
        public bool IsPortfolioComponent { get; set; }
        public IList<DistributionRecord> Distributions { get; set; }
        public NodeRecord Parent { get; set; }
    }
}

GoalBasedMvc/GoalBasedMvc/Models/Node/NodeViewModel.cs
using System.Collections.Generic;

namespace GoalBasedMvc.Models
{
    public class NodeViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
        public string NetworkName { get; set; }
        public string NetworkUrl { get; set; }
        public double? InitialPrice { get; set; }
        public double? InitialInvestment { get; set; }
        public double? PortfolioWeight { get; set; }
        public bool IsPortfolioComponent { get; set; }

        public IList<DistributionViewModel> Distributions { get; set; }
        public StatisticViewModel Statistics { get; set; }
        public IList<HistogramDatum> Histogram { get; set; }
        public NodeViewModel Parent { get; set; }
    }
}

GoalBasedMvc/GoalBasedMvc/Controllers/NetworkController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using GoalBasedMvc.Models;
using GoalBasedMvc.Logic;
using System.Linq;

namespace GoalBasedMvc.Controllers
{
    public class NetworkController : Controller
    {
        private readonly INetworkService _networkService;
        private readonly INodeService _nodeService;

        public NetworkController(
            INetworkService networkService,
            INodeService nodeService
            )
        {
            _networkService = networkService;
            _nodeService = nodeService;
        }

        public IActionResult Index()
        {
            var networks = _networkService.GetNetworks();
            return View(networks);
        }

        [HttpGet("{url}")]
        public IActionResult Get(string url)
        {
            var network = _networkService.GetNetworkByUrl(url);
            return View(network);
        }

        [HttpGet("{url}/nodes")]
        public IActionResult Nodes(string url)
        {
            var network = _networkService.GetNetworkByUrl(url);
            return View("Nodes", network);
        }

        [HttpGet("{networkUrl}/nodes/{nodeUrl}")]
        public IActionResult Node(string networkUrl, string nodeUrl)
        {
            var nodeOnly = _nodeService.GetNodeByUrl(nodeUrl, networkUrl);
            var network = _networkService.GetNetworkByUrl(networkUrl);
            var node = network.Nodes[nodeOnly.Id];
            node.NetworkName = network.Name;
            node.NetworkUrl = network.Url;
            return View("Node", node);
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }


}
}

GoalBasedMvc/GoalBasedMvc/Views/Network/Get.cshtml
@model GoalBasedMvc.Models.NetworkViewModel

@section Scripts{

    <script>
        $(function () {

            var network = @Html.Raw(Json.Serialize(Model));

            var cashFlowsChart, goalAttainmentChart;

            init();

            function init() {
                Chart.defaults.scale.gridLines.display = false;
                createCashFlowsGraph();
                createGoalAttainmentGraph();
                setPortfolioStatistics();
                createPortfolioHistogramGraph();
            }

            function setPortfolioStatistics() {
                $('#portfolioMean').html(network.portfolio.statistics.mean.toFixed(3));
                $('#portfolioStdev').html(network.portfolio.statistics.stdev.toFixed(3));
                $('#portfolioSkew').html(network.portfolio.statistics.skew.toFixed(3));
                $('#portfolioKurt').html(network.portfolio.statistics.kurt.toFixed(3));
            }

            function createCashFlowsGraph() {
                var cashFlows = network.cashFlows.map(function (cashFlow) { return cashFlow.cost });
                var cashFlowsLabels = getTimeSeriesGraphLabels(cashFlows);
                var cashFlowsCtx = document.getElementById("cashFlowsChart").getContext("2d");

                cashFlowsChart = new Chart(cashFlowsCtx, {
                    type: 'line',
                    data: {
                        labels: cashFlowsLabels,
                        datasets: [{
                            label: 'Cash Flow',
                            lineTension: 0,
                            data: cashFlows
                        }]
                    },
                    options: {
                        legend: {
                            display: false
                        },
                        scales: {
                            yAxes: [{
                                ticks: {
                                    fontSize: 14,
                                    fontStyle: 'bold'
                                }
                            }],
                            xAxes: [{
                                ticks: {
                                    fontSize: 14,
                                    fontStyle: 'bold'
                                }
                            }]
                        }
                    }
                });
            }

            function createGoalAttainmentGraph() {
                var goalAttainmentLabels = getTimeSeriesGraphLabels(network.portfolio.successProbabilities);
                var goalAttainmentCtx = document.getElementById("goalAttainmentChart").getContext("2d");

                goalAttainmentChart = new Chart(goalAttainmentCtx, {
                    type: 'line',
                    data: {
                        labels: goalAttainmentLabels,
                        datasets: [{
                            label: 'Goal Attainment',
                            lineTension: 0,
                            data: network.portfolio.successProbabilities
                        }]
                    },
                    options: {
                        legend: {
                            display: false
                        },
                        scales: {
                            yAxes: [{
                                ticks: {
                                    fontSize: 14,
                                    fontStyle: 'bold'
                                }
                            }],
                            xAxes: [{
                                ticks: {
                                    fontSize: 14,
                                    fontStyle: 'bold'
                                }
                            }]
                        }
                    }
                });
            }

            function createPortfolioHistogramGraph() {
                var labels = network.portfolio.histogram.map(function (point) { return point.interval.toFixed(0) });
                var data = network.portfolio.histogram.map(function (point) { return point.frequency });
                var goalAttainmentCtx = document.getElementById("portfolioHistogramChart").getContext("2d");

                goalAttainmentChart = new Chart(goalAttainmentCtx, {
                    type: 'bar',
                    data: {
                        labels: labels,
                        datasets: [{
                            label: 'Frequency',
                            data: data
                        }]
                    },
                    options: {
                        legend: {
                            display: false
                        },
                        scales: {
                            yAxes: [{
                                gridLines: {
                                    drawBorder: false,
                                },
                                ticks: {
                                    display: false
                                }
                            }],
                            xAxes: [{
                                ticks: {
                                    fontSize: 14,
                                    fontStyle: 'bold',
                                    autoSkip: true,
                                    maxTicksLimit: 20
                                }
                            }]
                        }
                    }
                });
            }

            function getTimeSeriesGraphLabels(data) {
                var labels = [];
                for (var cnt = 0; cnt < data.length; cnt++) {
                        labels.push("Year " + cnt);
                }
                return labels;
            }

         });
    </script>

}

<div class="panel panel-primary">

    <ol class="breadcrumb">
        <li><a href="/">Networks</a></li>
        <li class="active">@Model.Name</li>
        <li>@Html.ActionLink("Nodes", "Nodes", "Network")</li>
    </ol>

    <form class="panel-body">

        <div id="goalAttainmentContainer" class="panel panel-info">
            <div class="panel-heading">
                <h3 class="panel-title">Probability of Success</h3>
            </div>

            <div class="panel-body">
                <div class="row">
                    <div class="col-md-10 col-md-offset-1">
                        <canvas id="goalAttainmentChart"></canvas>
                    </div>
                </div>
            </div>
        </div>

        <div class="panel panel-info">
            <div class="panel-heading">
                <h3 class="panel-title">Cash Flows</h3>
            </div>

            <div class="panel-body">
                <div class="row">
                    <div class="col-md-10 col-md-offset-1">
                        <canvas id="cashFlowsChart"></canvas>
                    </div>
                </div>
            </div>
        </div>

        <div class="panel panel-info">
            <div class="panel-heading">
                <h3 class="panel-title">Portfolio</h3>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-10 col-md-offset-1">
                        <canvas id="portfolioHistogramChart"></canvas>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-10 col-md-offset-1">
                        <div class="table-responsive">
                            <table class="table table-striped">
                                <thead>
                                    <tr>
                                        <th>Average</th>
                                        <th>Volatility</th>
                                        <th>Skewness</th>
                                        <th>Kurtosis</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td id="portfolioMean"></td>
                                        <td id="portfolioStdev"></td>
                                        <td id="portfolioSkew"></td>
                                        <td id="portfolioKurt"></td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>

</form>

</div>

GoalBasedMvc/GoalBasedMvc/Views/Network/Index.cshtml
@model IEnumerable<GoalBasedMvc.Models.NetworkRecord>

<div class="panel panel-primary">

    <ol class="breadcrumb">
        <li class="active">Networks</li>
    </ol>

    <table class="table table-striped">
        <thead>
            <tr>
                <th>Name</th>
                <th>Url</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td><a asp-area="" asp-controller="Network" asp-action="Get" asp-route-url="@item.Url">@item.Name</a></td>
                    <td>@item.Url</td>
                </tr>
            }
        </tbody>
    </table>

</div>

GoalBasedMvc/GoalBasedMvc/Views/Network/Nodes.cshtml
@model GoalBasedMvc.Models.NetworkViewModel

<div class="panel panel-primary">

    <ol class="breadcrumb">
        <li><a href="/">Networks</a></li>
        <li>@Html.ActionLink(Model.Name, "Get", "Network", new {url = Model.Url})</li>
        <li class="active">Nodes</li>
    </ol>

    <form class="panel-body">

        <div class="panel panel-info">

            <div class="panel-heading">
                <h3 class="panel-title">Nodes</h3>
            </div>

            <div class="table-responsive">
                <table id="tblNodes" class="table table-striped">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Parent</th>
                            <th>Initial Investment</th>
                            <th>Initial Price</th>
                            <th>Portfolio Component?</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var node in Model.Nodes.Values)
                        {
                            <tr>
                                <td>@Html.ActionLink(node.Name, "Node", "Network", new {networkUrl = Model.Url, nodeUrl = node.Url })</td>
                                <td>@node.Parent?.Name</td>
                                <td>@node.InitialInvestment</td>
                                <td>@node.InitialPrice</td>
                                <td>@node.IsPortfolioComponent</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>


    </form>

</div>